# Generated by Django 2.2.3 on 2019-07-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haraj_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='isbn',
            new_name='Phone_number',
        ),
        migrations.RemoveField(
            model_name='add',
            name='number',
        ),
        migrations.AddField(
            model_name='add',
            name='city',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
