# Generated by Django 2.2.3 on 2019-07-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haraj_app', '0004_auto_20190730_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='publish_on',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='add',
            name='picture',
            field=models.ImageField(blank=True, upload_to='haraj_pics'),
        ),
    ]
